version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
            - node-v1-
      - run: yarn install
      - run: yarn lint
      - save_cache:
        paths:
          - ./node_modules
        key: node-v1-{{ checksum "yarn.lock" }}
